From ClaimSieve Require Import AuthorityCompressionCurrentState.

Print Assumptions current_state_is_additional_authority_boundary.
Print Assumptions current_revocation_blocks_execution.
Print Assumptions current_consumption_blocks_execution.
Print Assumptions current_policy_inactive_blocks_execution.
Print Assumptions current_identity_inactive_blocks_execution.
Print Assumptions current_campaign_inactive_blocks_execution.
Print Assumptions current_global_freeze_blocks_execution.
Print Assumptions current_campaign_suspension_blocks_execution.
Print Assumptions current_policy_replacement_blocks_execution.
Print Assumptions current_identity_replacement_blocks_execution.
Print Assumptions revocation_does_not_rewrite_historical_authority.
Print Assumptions global_freeze_does_not_rewrite_historical_authority.
Print Assumptions current_execution_implies_historical_authority.
